language: node_js
node_js:
  - '10.13.0'

cache:
  directories:
    - node_modules

before_install:
  - npm install -g typescript@3.1.6

script:
  - tsc --build
  - mkdir dist
  - cp -a index.html dist/
  - cp -a index.scss dist/
  - mkdir -p dist/scripts
  - cp -a scripts/*.js dist/scripts/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
